### ISSUE TITLE
Critical Error when there are too many Constraints

### ISSUE THREAD

**Issue by phikal** [neil-lindquist/linear-programming-glpk#6]
I was writing a test that generated 10000 trivial constraints, when I noticed that SBCL always died when evaluating it. LDB pointed me to [this line](https://github.com/firedrakeproject/glpk/blob/45156a549252849cad016366022aa1af50990613/src/env/alloc.c#L72) in GLPK, indicating that it's internal memory management overflowed.

It appears that the function `glp mem limit` has to be invoked at some point to increase the available memory, or in combination with `glp_mem_usage` to not allocate too much.

**Comment by phikal** [comment]
It might also be possible to make use of the fact that `xerror`/`glp_error` uses [`abort`](https://github.com/firedrakeproject/glpk/blob/45156a549252849cad016366022aa1af50990613/src/env/error.c#L55), as to install a signal handler that then throws a lisp error. [trivial-signal](https://github.com/guicho271828/trivial-signal) might help with that.

**Comment by neil-lindquist** [comment]
For reference, how many variables does your test use?

I'm coming up with a few possible solutions, all with potential down sides
* Your proposed approach of capturing the signal
  * the abort call is followed by exit, which I don't know how to prevent
  * Also glpk might be left in a bad intermediate state, if the code assumes that the process will die
* Make the memory limit another flag
  * Makes the user estimate how much memory they might need when working with problems that might go over the default
* Have the library estimate the amount needed for a problem and increase as needed
  * Might be difficult to accurately estimate, IDK what all gets allocated by GLPK

**Comment by neil-lindquist** [comment]
I think this issue might come from garbage collection, and thus the call to delete the problem object, isn't being done on the same thread as the creation.
If you delete the problem at the end of the solve function:
```diff
@@ -254,7 +254,9 @@
-      (trivial-garbage:finalize sol (lambda () (%delete-prob glpk-ptr)))
-      sol)))
+      ;(trivial-garbage:finalize sol (lambda () (%delete-prob glpk-ptr)))
+      sol)
+    (%delete-prob glpk-ptr)
+    nil))
```
Then, you can repeatedly evaluate the let in the following code
```common-lisp
(ql:quickload 'linear-programming-glpk)
(setf linear-programming:*solver* linear-programming-glpk:glpk-solver)
(let* ((vars (loop :repeat 10000 :collect (gensym)))
	 (problem (linear-programming:parse-linear-problem
		   `(min (+ . ,vars))
		   (loop :for var1 :in vars
			 :for var2 :in (rest vars)
			 :collect (list '= var1 var2))))
	 (solution (linear-programming:solve-problem problem))))
```

The best strategy I'm coming up with so far to fix this is to copy variable values into a lisp array and use that for `solution-variable` and friends.  Thoughts?

**Comment by phikal** [comment]
As long as the array doesn't overflow the heap (that shouldn't be the case), I think that that is the best solution. I'll try to submit a patch for that as soon as possible.

**Comment by neil-lindquist** [comment]
At the most extreme I can think of, this will at most double the max heap usage.  So this shouldn't reduce the maximum problem size too badly.

I had worked out a vague plan already, so I just made the changes and pushed them.  Tests are still passing, so it looks like it doesn't cause any huge problems.
